language: go
go:
  - 1.8
  - master
env:
  global:
    - GOARCH=amd64
    - GO_FOR_RELEASE=1.8
before_install:
  - go get github.com/AlekSi/zabbix-sender
  - go get github.com/denisenkom/go-mssqldb
  - go get gopkg.in/yaml.v2
notifications:
  email: false
